akamap = {
    ###########################################################################################################SPECIAL
    # acronym expansions
    "INTL FCStone Inc": ["International Assets Holding Corp", "FCStone Group"],
    "NFP Corp": "National Financial Partners",
    "NXXI Inc": "Nutrition 21 Inc",
    "CNX Gas Corp": "Consol Energy Inc",
    "WEX Inc": "Wright Express Corp",
    "LRAD Corp": "American Technology Corp",
    'RS Legacy Corp': 'RadioShack Corp',
    'L Brands Inc': 'Limited Brands Inc',
    'HP Inc': 'Hewlett-Packard Co', #DASH
    'Acas LLC': 'American Capital Ltd',
    'SLM Corp': 'Sallie Mae Corp',
    'Flex Ltd': 'Flextronics International Ltd',

    # straight up different name
    'Twenty-First Century Fox Inc': 'News Corporation',
    'Perrigo Corporation Ltd': 'Elan Corporation',
    'BlackBerry Ltd': ['Research In Motion Ltd', 'RIM'],
    'Mondelez International Inc': 'Kraft Foods Inc',
    'Chubb Ltd': 'Ace Ltd',
    'Anthem Inc': 'WellPoint Inc',
    'VEON Ltd': 'VimpelCom Ltd',
    'Blue Ridge Mountain Resources Inc': ['Magnum Hunter Resources Corp', 'Petro Resources Corp'],
    'Repsol Oil & Gas Canada Inc': 'Talisman Energy Inc',
    'Tegna Inc': 'Gannett Co Inc',
    'Hillshire Brands Co': 'Sara Lee Corp',
    'S&P Global Inc': ['McGraw-Hill Cos Inc', 'McGraw-Hill Companies Inc', 'McGraw-Hill Financial Inc'], #DASH
    'Leidos Holdings Inc': ['Science Applications International Corporation', 'SAIC'],
    'Keurig Green Mountain Inc': 'Green Mountain Coffee Roasters Inc',
    'Orbital ATK Inc': ['Alliant Techsystems Inc', 'Orbital Sciences Corp', 'ATK'],
    'Komatsu Mining Corp': 'Joy Global Inc',
    'Ionis Pharmaceuticals Inc': 'Isis Pharmaceuticals Inc',
    'Lanxess Solutions Us Inc': 'Chemtura',
    'United Continental Holdings Inc': 'UAL Corp',
    'American Outdoor Brands Corp': 'Smith & Wesson Holding Corp',
    'Energy Transfer Partners LP': 'Sunoco Logistics Partners LP',
    'Kate Spade & Co': 'Liz Claiborne Inc',
    'American Airlines Group Inc': 'AMR Corp',
    'Wendys Co': ["Wendy's", 'Triarc Cos Inc'],
    'Alpha Appalachia Holdings Inc': 'Massey Energy Co',
    'Westrock MWV LLC': 'MeadWestvaco Corp',
    'Targa Pipeline Partners LP': ['Atlas Pipeline Partners, L.P.', 'Atlas Energy Resources, LLC'],

    # straight up different, but it's just a nickname
    'Federal Home Loan Mortgage Corp': 'Freddie Mac',
    "Federal National Mortgage Association": "Fannie Mae",
    'China Petroleum & Chemical Corp': 'Sinopec',
    'Aluminum Corp of China Ltd': 'Chalco',
    'Laboratory Corporation of America Holdings': 'LabCorp',

    # foreign non-obvious acronyms / mergers / the likes
    "Mobil\'nye Telesistemy PAO": "MTS",
    'Petroleo Brasileiro SA Petrobras': 'Petrobras',
    'Arconic Inc': 'Alcoa',
    'Toronto-Dominion Bank': ['TD Bank', 'TD Canada Trust'],
    'Herc Holdings Inc': 'Hertz Global Holdings Inc',
    'Bank of Nova Scotia': 'Scotiabank',
    'ConocoPhillips': ['Conoco Inc', 'Phillips Petroleum Co'],
    'Kraft Heinz Foods Co': ['H. J. Heinz Co', 'HJ Heinz Co', 'Heinz'],

    # partial matches
    'Citigroup Inc': 'Citi',
    'GlaxoSmithKline PLC': 'Glaxo',
    'Walgreen Co': 'Walgreens',

    # special cases that almost fit a pattern but don't
    'Amazon.com Inc': 'Amazon Inc',
    'Bank of America Corp': ['BofA', 'B of A'],
    'E I du Pont de Nemours and Co': 'DuPont',
    'Bank of Montreal': 'BMO',
    'JPMorgan Chase & Co': ['JP Morgan Chase', 'JPMorganChase', 'JPM'],
    'Exxon Mobil Corp': 'ExxonMobil',
    'J C Penney Company Inc': 'J.C. Penney Co Inc',
    'Kohls Corp': "Kohl's Corp",
    "Dr.Reddy's Laboratories Ltd": 'Dr Reddys Laboratories',
    'Lions Gate Entertainment Corp': 'Lionsgate',
    'Canadian National Railway Co': 'CN Rail',
    'Canadian Pacific Railway Ltd': 'CP Rail',
    'Intercontinental Exchange Inc': ['IntercontinentalExchange Inc', 'ICE'],
    "Childrens Place Inc": ["The Children's Place Retail Stores, Inc.", "Children's Place Retail Stores, Inc."],

    #####################################################################################################SPECIAL
    # almost acronyms were it not for stopwords
    'Royal Bank of Scotland Group PLC': 'RBS',
    "Royal Bank of Canada": "RBC",
    'Canadian Imperial Bank of Commerce': 'CIBC',

    # acronyms
    "O I Corp": "OI Corp",
    "Semiconductor Manufacturing International Corp": "SMIC",
    "General Electric Co": "GE",
    'International Business Machines Corp': 'IBM',
    'American International Group Inc': 'AIG Inc',
    'General Motors Co': 'GM',
    'United Parcel Service Inc': 'UPS',
    'Advanced Micro Devices Inc': 'AMD',
    'Johnson & Johnson': ['JNJ', 'J&J'],
    'Procter & Gamble Co': 'P&G',
    'Banco Bilbao Vizcaya Argentaria S.A.': 'BBVA',
    'Automatic Data Processing Inc': 'ADP',
    'Taiwan Semiconductor Manufacturing Co Ltd': 'TSMC',
    'Electronic Arts Inc': 'EA',
    'American Electric Power Company Inc': 'AEP',
    'Archer Daniels Midland Co': 'ADM',
    'Texas Instruments Inc': 'TI',
    'United Microelectronics Corp': 'UMC',
    'Illinois Tool Works Inc': 'ITW',
    'Chicago Bridge & Iron Company NV': 'CB&I',

    ###################################################################################################SPECIAL
    # combo case
    'Bank of New York Mellon Corp': ['BNY Mellon', 'Mellon'],
    'Fiat Chrysler Automobiles NV': ['FCA', 'Chrysler Automobiles'],

    # name starts in middle of official name
    "Telefonaktiebolaget LM Ericsson": "Ericsson",
    'Royal Dutch Shell PLC': 'Shell',
    'BHP Billiton PLC': 'Billiton',
    'Banco Santander SA': 'Santander',
    'Walt Disney Co': 'Disney',
    'Koninklijke Philips NV': 'Philips',
    'Eli Lilly and Co': 'Lilly',
    'Charles Schwab Corp': 'Schwab',
    'ZF TRW Automotive Holdings Corp': 'TRW Automotive Holdings Corp',
    
    # helped
    "Allergan plc": "ACTAVIS plc",
    "XPO CNW Inc": "Con-Way Inc" ,
    "Gates Worldwide Ltd": "Tomkins PLC",
    "Tivity Health Inc": "HEALTHWAYS INC ",
    "Welltower Inc": "Health Care REIT",
    "Merck & Co Inc": "Schering-Plough Inc", #TODO hand changed entry, might be wrong
    "Axon Enterprise Inc": "TASER INTERNATIONAL INC",
    "T-Mobile US Inc": "METROPCS COMMUNICATIONS INC",
    "Edgewell Personal Care Co": "ENERGIZER HOLDINGS INC",
    "W W Grainger Inc": ["WW GRAINGER INC", " W.W. GRAINGER INC", "GRAINGER"],
    "Viavi Solutions Inc" : ["JDSU Inc", "JDS Inc"],
    "Alphabet Inc": "GOOGLE llc",
    "Semiconductor Manufacturing International Corp" : "SMIC",
    "Mitsubishi UFJ Financial Group Inc": ["MUFG", "Public Service Enterprise Group Inc"],
    "Vale SA": "CVRD",
    "CoreCivic Inc": "CORRECTIONS CORP",
    "Public Service Enterprise Group Inc": "PSEG",
    "SunEdison Inc": "MEMC ELECTRONIC MATERIALS INC",
    "VEREIT Inc": "AMERICAN REALTY CAPITAL PROPERTIES",
    "United Technologies Corp": "UTC",
    "Innoviva Inc": ["Theravance Inc", "Astellas and Theravance Inc"],
    "Companhia Siderurgica Nacional": "CSN",
    #"Eaton Vance Corp": 0,
    "EnLink Midstream Partners LP": "CROSSTEX ENERGY LP",
    "IRC Retail Centers Inc": "Inland Real Estate Corporation",
    "Westinghouse Air Brake Technologies Corp": "WABTEC CORP",
    "Caleres Inc": "BROWN SHOE CO INC",
    "Valeant Pharmaceuticals International Inc": ["BIOVAIL CORP", "Bausch Health Cos Inc"],
    "E. W. Scripps Co": ["SCRIPPS Co"," EW SCRIPPS CO"],
    "Southern Company Gas": " AGL CAPITAL CORP",
    "Banco Bradesco SA": "BRADESCO",
    "United States Steel Corp": ["U.S. steel company", "US STEEL CORP"],
    "Infor (US) Inc": "Lawson Software Inc" ,
    "Qorvo US Inc": "TRIQUINT SEMICONDUCTOR INC",
    "Boardriders Inc": "Quiksilver Inc",
    "Beam Suntory Inc": "FORTUNE BRANDS INC" ,
    "II-VI Optoelectronic Devices Inc": "ANADIGICS INC",
    "Microsemi Storage Solutions Inc": "PMC-SIERRA INC",
    "Pilgrims Pride Corp": "PILGRIM'S PRIDE",
    "Hycroft Mining Corp": ["Allied Nevada Gold Corp", "Vista Gold and Allied Nevada"],
    "Caseys General Stores Inc": "CASEY'S GENERAL STORES INC",
    "Grupo Televisa SAB": "Televisa",
    "WestRock RKT Co": ["Rock-Tenn Company", "ROCKTENN"],
    "Dell Software Inc": "Quest Software Inc",
    "Oracle America Inc": "Sun Microsystems",
    "Shire Viropharma Inc": "VIROPHARMA INC",
    "World Wrestling Entertainment Inc": "WWE",
    "Consolidated Edison Inc": ["Con Edison", "ConEdison"],
    "Dominion Questar Corp": "Questar Corp",
    "HGST Technologies Santa Ana Inc": ["SIMPLETECH INC", "STEC INC"],
    "Fair Isaac Corp": "FICO",
    "CalAtlantic Group Inc": "STANDARD PACIFIC CORP",
    #"Brinks Co": 0,
    #"Morgan Stanley": ?, #TODO
    "Relx NV": "Reed Elsevier PLC",
    "Latam Airlines Group SA": "LAN Airlines",
    "Intrepid Healthcare Services Inc": ["IPC THE HOSPITALIST CO INC", "IPC HEALTHCARE INC"],
    "ManpowerGroup Inc": "Manpower Inc",
    "TreeHouse Private Brands Inc": "Ralcorp Holdings",
    "Prologis Inc": "AMB Property",
    "Total System Services Inc": "TSYS",
    "Equity Commonwealth": ["HRPT Properties Trust","CommonWealth REIT" ],
    "Dun & Bradstreet Corp": "D&B",
    "Cimpress NV": "VISTAPRINT LTD",
    "Meritor Inc": "ArvinMeritor INC",
    "International Flavors & Fragrances Inc": "IFF",
    "Integer Holdings Corp": "GREATBATCH",
    "Partylite Inc": "BLYTH",
    "Integrated Device Technology Inc": "IDT",
    "Tower Semiconductor Ltd": "TowerJazz",
    "National Bank of Greece SA": ["NBG", "Nat. Bank Of Greece"],
    "Kinder Morgan Inc": "KINDER MORGAN",
    "Life Storage Inc": "SOVRAN SELF STORAGE",
    "Roust Corp": "CENTRAL EUROPEAN DISTRIBUTION",
    "American Zinc Recycling LLC": "HORSEHEAD HOLDING",
    "WEC Energy Group Inc": "WISCONSIN ENERGY CORP",
    "FirstCash Inc": "FIRST CASH FINANCIAL SERVICES INC",
    "Catalyst Biosciences Inc": "TARGACEPT INC",
    "Mallinckrodt Ard Inc": "QUESTCOR PHARMACEUTICALS INC",
    "Silicon Graphics International Corp": ["RACKABLE SYSTEMS INC ","SGI"],
    "Infineon Technologies Americas Corp": "INTERNATIONAL RECTIFIER",
    "Telecom Italia SpA": ["Pirelli", "Telefonica", "TELCO ITALIAN"],
    "PVH Corp": "Phillips-Van Heusen Corporation",
    "Hope Bancorp Inc": ["NARA BANK NATIONAL ASSOCIATION", "Nara Bancorp Inc","BBCN BANCORP INC"],
    "Belmond Ltd": "ORIENT-EXPRESS HOTELS LTD",
    "Becton Dickinson and Co": "BD",
    "Catamaran Corp": ["SXC Health Solutions", "Systems Xcellence"],
    "W. R. Grace & Co": "Grace",
    "Crestwood Equity Partners LP": ["INERGY HOLDINGS LP", "INERGY MIDSTREAM"],
    "Fomento Economico Mexicano SAB de CV": "Femsa",
    "Everi Holdings Inc": ["Global Cash Access", "GCA"],
    "KP Pharmaceuticals LLC": "King Pharmaceuticals",
    "Investment Technology Group Inc": "ITG",
    "BWX Technologies Inc": ["BABCOCK & WILCOX CO", "B&W"],
    "AGNC Investment Corp": ["AMERICAN CAPITAL AGENCY CORP"],
    "Conversant Inc": "ValueClick INC",
    "Ingredion Inc": "CORN PRODUCTS INTERNATIONAL INC",
    "Eversource Energy": ["NU", "NORTHEAST UTILITIES CO"],
    "Axiall Corp": "GEORGIA GULF CORP",
    "PVR Partners LP": "Penn Virginia Resource Partners LP",
    "Statoil Exploration Co": "BRIGHAM EXPLORATION CO",
    "HollyFrontier Corp": "HOLLY ENERGY PARTNERS LP",
    "Archrock Inc": ["Exterran Holdings", "EXTERRAN PARTNERS L P"],
    "Oracle Taleo LLC": "TALEO CORP",
    "Aretec Group Inc": "RCS CAPITAL CORPORATION",
    "Huaneng Power International Inc": "SHH Margin Trading",
    "TE Connectivity Ltd": ["Tyco International", "TYCO ELECTRONICS LTD"],
    "CBRE Group Inc": "CB Richard Ellis Group",
    "SRC Energy Inc": "SYNERGY RESOURCES CORP",
    "Fanhua Inc": "CNINSURE INC",
    "PulteGroup Inc": "PULTE",
    "Essendant Inc": "UNITED STATIONERS INC",
    "Imagination Technologies LLC": "MIPS Technologies",
    "WEX Inc": "Wright Express",
    "Archrock Partners LP": ["EXTERRAN PARTNERS LP", "EXTERRAN HOLDINGS INC"],
    "Potash Corporation of Saskatchewan Inc": "PotashCorp",
    "Resolute Forest Products Inc": "ABITIBIBOWATER INC",
    "PepsiCo Inc": ["Pepsi-Cola", "Pepsi Beverages Company"],
    "Wec Acquisition Corp": ["WPS RESOURCES CORP", "INTEGRYS ENERGY GROUP"],
    "Central European Media Enterprises Ltd": "CME",
    "Vectra Co": ["OM Group", "OMG"],
    "Erin Energy Corp": ["Pacific Asia Petroleum, Inc.", "CAMAC Energy"],
    "American Express Co": "Amex",
    "Apartment Investment and Management Co": "Aimco",
    "Spectra Energy Partners LP": "SPECTRA ENERGY",
    "J M Smucker Co": ["Smucker", "JM SMUCKER"],
    "Coinstar LLC": "Outerwall Inc",
    "Fidelity National Information Services Inc": ["FIDELITY NATIONAL FINANCIAL INC", "FIS"],
    "Electronics for Imaging Inc": "EFI",
    "ILG Inc": ["INTERVAL LEISURE GROUP INC", "Interval International"],
    "Black Knight InfoServ LLC": ["LENDER PROCESSING SERVICES INC", "LPS"],
    "Albany Molecular Research Inc": "AMRI",
    "B456 Systems Inc": "A123 SYSTEMS INC",
    "CommScope Connectivity LLC": "ADC",
    "Exelon Corp": "PECO",
    "Spire Inc": "LACLEDE GROUP INC",
    "HP Enterprise Services LLC": ["EDS", "ELECTRONIC DATA SYSTEMS CORP"],
    "Time Warner Cable Inc": "TWC",
    "AstraZeneca PLC": "Astra",
    "C R Bard Inc": ["Bard", "C.R. BARD INC"],
    "Enlink Midstream Inc": "CROSSTEX ENERGY LP",
    "Biovia Corp": "ACCELRYS INC",
    "Fang Holdings Ltd": "SOUFUN HOLDINGS LTD",
    "Livestyle Inc": "SFX ENTERTAINMENT INC",
    "Enbridge Energy Management LLC": "ENBRIDGE ENERGY PARTNERS LP",
    "XPO Intermodal Inc": "PACER INTERNATIONAL INC",
    "Granite Real Estate Inc": ["MI Developments Inc", "MID"],
    "Radial Commerce Inc": "GSI COMMERCE INC",
    "SpartanNash Co": "SPARTAN STORES INC",
    "Pharmaceutical Product Development Inc": "PPD INC",
    "British American Tobacco PLC": "BAT",
    "Bayer Essure Inc": "CONCEPTUS INC",
    "TerraVia Holdings Inc": "SOLAZYME INC",
    "Energy Future Holdings Corp": "TXU Corp",
    "J B Hunt Transport Services Inc": "J.B. HUNT TRANSPORT SERVICES INC",
    "PTC Inc": "PARAMETRIC TECHNOLOGY CORP",
    "ZCO Liquidating Corp": "OCZ TECHNOLOGY GROUP",
    "Fresenius Medical Care AG & Co KGaA": "FMC",
    "Alere Inc": "Inverness Medical Innovations",
    "ArcBest Corp": "ARKANSAS BEST CORPORATION",
    "ANN Inc": "ANNTAYLOR STORES CORP",
    "Popeyes Louisiana Kitchen Inc": "AFC ENTERPRISES INC",
    "Macy's Inc": "FEDERATED DEPARTMENT STORES INC",
    "CNO Financial Group Inc": "CONSECO INC",
    "Everi Games Holding Inc": "MULTIMEDIA GAMES HOLDING COMPANY INC",
    "Blucora Inc": "INFOSPACE INC",
    "Gener8 Maritime Inc": "GENERAL MARITIME CORP",
    "ANI Pharmaceuticals Inc": ["BIOSANTE PHARMACEUTICALS INC", "ANTARES PHARMA INC"],
    "P H Glatfelter Co": ["GLATFELTER", "PH GLATFELTER CO"],
    "Sarepta Therapeutics Inc": "AVI BIOPHARMA INC",
    "Ship Finance International Ltd": "SFL",
    "Compania de Minas Buenaventura SAA": "BUENAVENTURA",
    "Payless Inc": "Collective Brands Inc",
    #"Telefonica SA": "Telefonica",
    "Super Micro Computer Inc": "Supermicro",
    "SHFL entertainment Inc": ["SHUFFLE MASTER INC"],
    "DFC Global Corp": "Dollar Financial Corp",
    "Mallinckrodt Hospital Products Inc": "CADENCE PHARMACEUTICALS INC",
    "Atlantica Yield PLC": "ABENGOA YIELD PLC",
}